version: '2'

services:

  kafka:
    image: quay.io/strimzi/kafka:0.37.0-kafka-3.5.1
    command: [
      "sh", "-c",
      "./bin/kafka-storage.sh format -t $$(./bin/kafka-storage.sh random-uuid) -c ./config/kraft/server.properties && ./bin/kafka-server-start.sh ./config/kraft/server.properties"
    ]
    ports:
    - "9092:9092"    
    environment:
      LOG_DIR: "/tmp/logs"
